services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: havens_db
      MYSQL_ROOT_PASSWORD: Juanes068
    ports:
      - "3307:3306"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A havens worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
