# Generated by Django 4.2.30 on 2026-06-19 05:16

from django.db import migrations
from django.utils.text import slugify


def populate_subdomain(apps, schema_editor):
    """Generate unique subdomains for existing communities"""
    Community = apps.get_model('core', 'Community')
    
    for idx, community in enumerate(Community.objects.all()):
        if not community.subdomain:
            # Generate subdomain from community name
            base_subdomain = slugify(community.name)[:50] or f"community-{community.id}"
            subdomain = base_subdomain
            
            # Ensure uniqueness
            counter = 1
            while Community.objects.filter(subdomain=subdomain).exclude(id=community.id).exists():
                subdomain = f"{base_subdomain}-{counter}"
                counter += 1
            
            community.subdomain = subdomain
            community.save()


def reverse_subdomain(apps, schema_editor):
    """Reverse operation - clear subdomains (optional)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_subdomain, reverse_subdomain),
    ]
