# Generated by Django 4.2.30 on 2026-07-27 18:46

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_hobbycategory_userprofile_invite_code_hobby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='code',
            field=models.CharField(default=core.models.generate_6char_invite_code, editable=False, max_length=36, unique=True),
        ),
    ]
