# Generated by Django 4.2.30 on 2026-08-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_event_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
