# Generated by Django 4.2.30 on 2026-08-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_match_initiator_match_status_match_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_virtual',
            field=models.BooleanField(default=False),
        ),
    ]
