# Generated by Django 4.2.30 on 2026-08-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='age_range',
            field=models.CharField(blank=True, default='All Ages', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='max_age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='min_age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
