# Generated by Django 4.2.30 on 2026-08-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_event_age_range_event_max_age_event_min_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='age_range',
            field=models.CharField(blank=True, default='All Ages', max_length=100),
        ),
        migrations.AddField(
            model_name='community',
            name='max_age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='min_age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
