# Generated by Django 4.2.30 on 2026-08-27 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_community_age_range_community_max_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircleMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_messages', to='core.community')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Circle Message',
                'verbose_name_plural': 'Circle Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
